services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dev_db
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev_pass
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # definiere einen dev Dockerfile, der npm run dev macht
    ports:
      - "5173:5173"  # Vite default dev port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
