services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    expose:
      - "8080"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    command: ["java", "-jar", "app.jar"]

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile.dev
    env_file:
      - .env
    expose:
      - "5173" # Vite Dev Server
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  proxy:
    image: nginx:1.23-alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -q"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_dev:
