services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./backend/.env:/app/.env:ro
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile # definiere einen dev Dockerfile, der npm run dev macht
    ports:
      - "80:80"  # Vite default dev port
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.env:/app/.env:ro
    env_file:
      - ./frontend/.env
    networks:
      - app-network

  postgres:
    image: postgres:15
    env_file:
      - ./postgres/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
