services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # definiere einen dev Dockerfile, der npm run dev macht
    ports:
      - "5173:5173"  # Vite default dev port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
