# === Development Stage ===
FROM node:22-alpine

# Arbeitsverzeichnis im Container
WORKDIR /app

# Abhängigkeiten installieren
COPY frontend/package*.json ./
RUN npm install

# Restlichen Code wird über Volume gemountet, daher hier optional
# COPY frontend/. .

# Port für Vite
EXPOSE 5173

# Dev Server starten
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

